[versions]
compileSdk = "34"
minSdk = "28"
targetSdk = "34"
appVersion = "1.0.0"
versionCode = "1"

# kotlin
kotlin = "1.9.10"
kotlinx-serialization-json = "1.6.1"
kotlinx-serialization-converter = "1.0.0"
kotlinx-coroutines = "1.7.3"

# android
corektx = "1.12.0"
appcompat = "1.6.1"
activity = "1.8.2"
lifecycle = "2.6.2"
navigation = "2.7.6"
dagger-hilt = "2.50"
fragment-ktx = "1.6.2"
splash-screen = "1.0.1"
paging = "3.1.1"
room = "2.5.0"
security = "1.1.0-alpha06"
swipe-refresh-layout = "1.1.0"

# material + google
material = "1.11.0"
accompanist = "0.32.0"
in-app-update = "2.1.0"
google-services = "4.4.0"
admob = "22.4.0"

# test
junit = "4.13.2"
androidx-test-junit = "1.1.5"
androidx-test-espresso = "3.5.1"

# gradle
agp = "8.0.2"
kspplugin = "1.9.10-1.0.13"

# third party
okhttp = "4.12.0"
retrofit = "2.9.0"
timber = "5.0.1"
coil = "2.5.0"
ktlint = "12.0.3"
constraintlayout = "2.1.4"
dot-indicator = "5.0"
kakao = "2.19.0"

[libraries]
# kotlin
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-gradleplugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlin-coroutines-google-play = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

# android
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "corektx" }
lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "splash-screen" }
paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
paging-domain = { module = "androidx.paging:paging-common", version.ref = "paging" }
navigation_fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation_ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
shared-security = { module = "androidx.security:security-crypto-ktx", version.ref = "security" }
swipe-refresh-layout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipe-refresh-layout" }

# dagger-hilt
hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
hilt-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "dagger-hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger-hilt" }
hilt-testing-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt" }

# google
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }

# test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

# third party
ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-converter" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }

dot-indicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dot-indicator" }

kakao-login = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakao" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspplugin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
lifecycle = ["lifecycle", "lifecycle-viewmodel", "lifecycle-livedata"]
retrofit = ["retrofit", "retrofit-kotlin-serialization-converter", "okhttp-bom", "okhttp", "okhttp-logging-interceptor"]
androidx-android-test = ["androidx-test-espresso", "androidx-test-junit"]
room = ["room-runtime", "room-compiler", "room-ktx"]